services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: visits
    volumes:
      - node-volume:/var/lib/mysql
    networks:
      - node-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$password"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-net

volumes:
  node-volume:

networks:
  node-net: